apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: demo
  version: "1.28"
  region: us-east-1
managedNodeGroups:
  - name: demo-nodes
    instanceType: t2.small
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
