apiVersion: v1
kind: Service
metadata:
  name: borrower-clusterip-srv
  labels:
    app: borrower
spec:
  type: ClusterIP
  selector:
    app: borrower
  ports:
    - name: borrower-port
      protocol: TCP
      port: 80
      targetPort: 8080
