apiVersion: v1
kind: Service
metadata:
  name: loan-clusterip-srv
  labels:
    app: loan
spec:
  type: ClusterIP
  selector:
    app: loan
  ports:
    - name: loan-port
      protocol: TCP
      port: 80
      targetPort: 8080
