apiVersion: apps/v1
kind: Deployment
metadata:
  name: borrower-depl
  labels:
    app: borrower
spec:
  replicas: 2
  selector:
    matchLabels:
      app: borrower
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: borrower
    spec:
      containers:
        - name: borrower-containers
          image: luisjavm3/creso-k8s-borrower:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 200m
