apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-depl
  labels:
    app: loan
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loan
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: loan
    spec:
      containers:
        - name: loan-containers
          image: luisjavm3/creso-k8s-loan:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 200m
